#!/usr/bin/env sh

. "$(dirname "$0")/helper"

if use_selection; then
    sed -z 's|'"$PWD/"'||g' < "$selection" | xargs -0 dragon --all >/dev/null 2>&1 &
else
    if [ -n "$1" ] && [ -e "$1" ]; then
        dragon "$1" >/dev/null 2>&1 &
    fi
fi
