#!/usr/bin/env bash

TMPDIR=${TMPDIR:-/tmp}
NNN_PARENT=${NNN_FIFO#*.}
[ "$NNN_PARENT" -eq "$NNN_PARENT" ] 2>/dev/null || NNN_PARENT="" # Make empty if non-numeric
ENVVARS=(
  "PWD=$PWD"
  "PATH=$PATH"
  "NNN_FIFO=$NNN_FIFO"
  "NNN_PAGER=${NNN_PAGER:-less -P?n -R}"
  "NNN_BATTHEME=${NNN_BATTHEME:-ansi}"
  "NNN_BATSTYLE=${NNN_BATSTYLE:-numbers}"
  "NNN_PREVIEWWIDTH=${NNN_PREVIEWWIDTH:-1920}"
  "NNN_PREVIEWHEIGHT=${NNN_PREVIEWHEIGHT:-1080}"
  "NNN_PREVIEWDIR=${NNN_PREVIEWDIR:-$TMPDIR/nnn/previews}"
  "FIFOPID=$TMPDIR/nnn-previews-fifopid.$NNN_PARENT"
  "FIFOPATH=$TMPDIR/nnn-previews-fifo.$NNN_PARENT"
  "PREVIEWPID=$TMPDIR/nnn-previews-previewpid.$NNN_PARENT"
  "CURSEL=$TMPDIR/nnn-previews-selection.$NNN_PARENT"
)

trap '' PIPE
exists() { type "$1" >/dev/null 2>&1 ;}
pkill() { command pkill "$@" >/dev/null 2>&1 ;}
prompt() { clear; printf "%b" "$@"; cfg=$(stty -g); stty raw -echo; head -c 1; stty "$cfg" ;}
pidkill() {
    if [ -f "$1" ]; then
        PID="$(cat "$1" 2>/dev/null)" || return 1
        kill "$PID" >/dev/null 2>&1
        RET=$?
        wait "$PID" 2>/dev/null
        return $RET
    fi
    return 1
}

start_preview() {
    ENVVARS+=("PREVIEW_MODE=1")
    ENVVARS=("${ENVVARS[@]/#/--env=}")
    kitty @ goto-layout splits
    # Trying to use kitty's integrated window management as the split window.
    kitty @ launch --no-response --keep-focus --cwd "$PWD" "${ENVVARS[@]}" --location "vsplit" "$0" "$1"
}

toggle_preview() {
    export "${ENVVARS[@]}"

    if pidkill "$FIFOPID"; then
        [ -p "$NNN_PPIPE" ] && printf "0" > "$NNN_PPIPE"
        pidkill "$PREVIEWPID"
    else
        [ -p "$NNN_PPIPE" ] && printf "1" > "$NNN_PPIPE"
        start_preview "$1"
    fi
}

fifo_pager() {
    cmd="$1"
    shift

    # We use a FIFO to access $NNN_PAGER PID in jobs control
    mkfifo "$FIFOPATH" || return

    $NNN_PAGER < "$FIFOPATH" &
    printf "%s" "$!" > "$PREVIEWPID"

    (
        exec > "$FIFOPATH"
        if [ "$cmd" = "pager" ]; then
            bat --terminal-width="$cols" --decorations=always --color=always \
                --paging=never --style="$NNN_BATSTYLE" --theme="$NNN_BATTHEME" "$@" &
        else
            "$cmd" "$@" &
        fi
    )

    rm "$FIFOPATH"
}

# Binary file: show file info inside the pager
print_bin_info() {
    printf -- "-------- \033[1;31mBinary file\033[0m --------\n"
    file -b "$1"
}

handle_mime() {
    case "$2" in
        image/jpeg) image_preview "$cols" "$lines" "$1" ;;
        image/gif) generate_preview "$cols" "$lines" "$1" "gif" ;;
        image/*) generate_preview "$cols" "$lines" "$1" "image" ;;
        application/font*|application/*opentype|font/*) generate_preview "$cols" "$lines" "$1" "font" ;;
        application/*spreadsheet) generate_preview "$cols" "$lines" "$1" "office" ;;
        application/zip) fifo_pager unzip -l "$1" ;;
        text/troff) fifo_pager man -Pcat -l "$1" ;;
        *) handle_ext "$1" "$3" "$4" ;;
    esac
}

handle_ext() {
    case "$2" in
        pdf) generate_preview "$cols" "$lines" "$1" "pdf" ;;
        gz|bz2) fifo_pager tar -tvf "$1" ;;
        md) fifo_pager lowdown -Tterm "$1" ;;
        htm|html|xhtml) fifo_pager lynx "$1" ;;
        7z|a|ace|alz|arc|arj|bz|cab|cpio|deb|jar|lha|lz|lzh|lzma|lzo\
        |rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z)
            fifo_pager atool -l "$1" ;;
        *) if [ "$3" = "bin" ]; then
               fifo_pager print_bin_info "$1"
           else
               fifo_pager pager "$1"
           fi ;;
    esac
}

preview_file() {
    clear

    # Detecting the exact type of the file: the encoding, mime type, and extension in lowercase.
    encoding="$(file -bL --mime-encoding -- "$1")"
    mimetype="$(file -bL --mime-type -- "$1")"
    ext="${1##*.}"
    [ -n "$ext" ] && ext="$(printf "%s" "${ext}" | tr '[:upper:]' '[:lower:]')"
    lines=$(tput lines)
    cols=$(tput cols)

    # Otherwise, falling back to the defaults.
    if [ -d "$1" ]; then
        cd "$1" || return
        # shellcheck disable=SC2012
        ls -F --group-directories-first | head -n "$((lines - 3))" | "$(dirname "$0")"/iconlookup -l "$cols" -B "\n" -b " "
        cd ..
    elif [ "${encoding#*)}" = "binary" ]; then
        handle_mime "$1" "$mimetype" "$ext" "bin"
    else
        handle_mime "$1" "$mimetype" "$ext"
    fi
}

generate_preview() {
  if [ ! -f "$NNN_PREVIEWDIR/$3.jpg" ] || [ -n "$(find -L "$3" -newer "$NNN_PREVIEWDIR/$3.jpg")" ]; then
        mkdir -p "$NNN_PREVIEWDIR/${3%/*}"
        case $4 in
            font) fontpreview -i "$3" -o "$NNN_PREVIEWDIR/$3.jpg" ;;
            gif) image_preview "$1" "$2" "$3"
                 return
                 ;;
            image) convert "$3" -flatten -resize "$NNN_PREVIEWWIDTH"x"$NNN_PREVIEWHEIGHT"\> "$NNN_PREVIEWDIR/$3.jpg" ;;
            office) libreoffice --convert-to jpg "$3" --outdir "$NNN_PREVIEWDIR/${3%/*}"
                    filename="$(printf "%s" "${3##*/}" | cut -d. -f1)"
                    mv "$NNN_PREVIEWDIR/${3%/*}/$filename.jpg" "$NNN_PREVIEWDIR/$3.jpg" ;;
            pdf) pdftoppm -jpeg -f 1 -singlefile "$3" "$NNN_PREVIEWDIR/$3" ;;
        esac
    fi
    if [ -f "$NNN_PREVIEWDIR/$3.jpg" ]; then
        image_preview "$1" "$2" "$NNN_PREVIEWDIR/$3.jpg"
    else
        fifo_pager print_bin_info "$3"
    fi
} >/dev/null 2>&1

image_preview() {
    clear
    exec >/dev/tty
    kitty +kitten icat --silent --scale-up --place "$1"x"$2"@0x0 --transfer-mode=stream --stdin=no "$3" &
    printf "%s" "$!" > "$PREVIEWPID"
}

winch_handler() {
    clear
    pidkill "$PREVIEWPID"
    preview_file "$(cat "$CURSEL")"
}

preview_fifo() {
    while read -r selection; do
        if [ -n "$selection" ]; then
            pidkill "$PREVIEWPID"
            [ "$selection" = "close" ] && break
            preview_file "$selection"
            printf "%s" "$selection" > "$CURSEL"
        fi
    done < "$NNN_FIFO"
    sleep 0.1 # make sure potential preview by winch_handler is killed
    pkill -P "$$"
}

if [ "$PREVIEW_MODE" -eq 1 ] 2>/dev/null; then
    preview_file "$PWD/$1"
    preview_fifo &
    printf "%s" "$!" > "$FIFOPID"
    printf "%s" "$PWD/$1" > "$CURSEL"
    trap 'winch_handler; wait' WINCH
    trap 'rm "$PREVIEWPID" "$CURSEL" "$FIFOPID" 2>/dev/null' INT HUP EXIT
    wait "$!" 2>/dev/null
else
    if [ ! -r "$NNN_FIFO" ]; then
        prompt "No FIFO available! (\$NNN_FIFO='$NNN_FIFO')\nPlease read Usage in '$0'."
    elif [ "$KITTY_WINDOW_ID" ] && [ -z "$TMUX" ] && [ -z "$KITTY_LISTEN_ON" ]; then
        prompt "\$KITTY_LISTEN_ON not set!\nPlease read Usage in '$0'."
    else
        toggle_preview "$1" &
    fi
fi
